### ISSUE TITLE
Open in Browser not working in Windows 10

### ISSUE THREAD

**Issue by Maldrek** [SudoKillMe/vscode-extensions-open-in-browser#38]
When running the open in browser/open in default browser I get an error: 

"Open browser failed!! Please check if you have installed the browser correctly!"

![screenshot 42](https://user-images.githubusercontent.com/34661287/49602708-bdb01900-f94e-11e8-8a81-747f1c8dec09.png)

I am not sure what is causing this issue, as it doesn't matter which browser I attempt to open in. Would love to see if this is an issue for anybody else

**Comment by adam6650261** [comment]
me tooooo

**Comment by adam6650261** [comment]
I want to know how to solve it

**Comment by Maldrek** [comment]
I tried everything and couldn't fix it. I finally just did a factory reset of my computer (kept my files) and I redownloaded everything and then it worked fine. Ridiculous solution, I know. But it worked.

**Comment by PapsOu** [comment]
I've got the same issue with this stack displayed in the extension host output :

```javascript
[2019-01-23 10:15:24.019] [exthost] [error] Error: spawn EACCES
	at _errnoException (util.js:1024:11)
	at ChildProcess.spawn (internal/child_process.js:323:11)
	at Object.exports.spawn (child_process.js:514:9)
	at module.exports (/home/papsou/.vscode/extensions/techer.open-in-browser-2.0.0/node_modules/opn/index.js:76:26)
	at Object.exports.open (/home/papsou/.vscode/extensions/techer.open-in-browser-2.0.0/out/util.js:28:5)
	at Object.exports.openDefault (/home/papsou/.vscode/extensions/techer.open-in-browser-2.0.0/out/index.js:27:12)
	at vscode.commands.registerCommand (/home/papsou/.vscode/extensions/techer.open-in-browser-2.0.0/out/extension.js:7:17)
	at e._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:501:455)
	at e.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:502:6)
	at t._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
	at t._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
	at t._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:657:126)
	at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
	at Socket.n._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) extension.openInDefaultBrowser
```

Does it helps ?

**Comment by plnorris97** [comment]
I have the same problem as well. I have set Chrome as my default and it was working a few months ago. So frustrated!

**Comment by Nisanech** [comment]
i have the same problem. I don't know how to solve it. Help me plis!!
